vrpn_client_node:
  ros__parameters:
    server: 192.168.0.196
    port: 3883
    frame_id: "world"
    use_server_time: false
    broadcast_tf: true
    refresh_tracker_frequency: 0.2
    update_frequency: 240.0
    rigid_body_whitelist: ["shadow"]